sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build
  - docker-compose run --rm app composer install
  - docker-compose run --rm app /code/vendor/bin/phpcs --standard=psr2 -n --ignore=vendor --extensions=php .
  - docker-compose run --rm app /code/vendor/bin/phpstan analyse --level=7 ./src

script:
  - docker-compose run --rm travis-php-test
  - docker-compose run --rm travis-lambda-deploy
  - docker-compose run --rm travis-lambda-test

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: docker-compose run --rm production-lambda-deploy && ./deploy.sh
  on:
    tags: true
