sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker build -t keboola/ex-email-attachments .
  - docker run --rm  keboola/ex-email-attachments composer install
  - docker run --rm  keboola/ex-email-attachments /code/vendor/bin/phpcs --standard=psr2 -n --ignore=vendor --extensions=php .
  - docker run --rm  keboola/ex-email-attachments /code/vendor/bin/phpstan analyse --level=7 ./src

script:
  - >-
    docker run --rm
    -e "AWS_ACCESS_KEY_ID=${CI_AWS_ACCESS_KEY_ID}"
    -e "AWS_SECRET_ACCESS_KEY=${CI_AWS_SECRET_ACCESS_KEY}"
    -e "DYNAMO_TABLE=${CI_DYNAMO_TABLE}"
    -e "EMAIL_DOMAIN=${CI_EMAIL_DOMAIN}"
    -e "REGION=${CI_REGION}"
    -e "S3_BUCKET=${CI_S3_BUCKET}"
    keboola/ex-email-attachments ./vendor/bin/phpunit

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
