version: "2"

services:

  app:
    build: .
    image: keboola/pigeon
    tty: true
    stdin_open: true

  tests:
    image: keboola/pigeon
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    entrypoint: /code/vendor/bin/phpunit

  dev:
    build: .
    image: keboola/pigeon
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
    environment:
      - KBC_PROJECTID

  xdebug:
    image: keboola/pigeon-xdebug
    build:
      context: .
      dockerfile: docker/xdebug/Dockerfile
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - CODECLIMATE_REPO_TOKEN
      - PHP_IDE_CONFIG
      - XDEBUG_CONFIG