version: "2"

services:

  app:
    build: .
    image: keboola/pigeon
    tty: true
    stdin_open: true

  test:
    image: keboola/pigeon
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    entrypoint: /code/vendor/bin/phpunit
    environment:
      - DYNAMO_TABLE
      - EMAIL_DOMAIN
      - REGION
      - S3_BUCKET
      - STACK_NAME
      - USER_ACCESS_KEY_ID
      - USER_SECRET_ACCESS_KEY

  dev:
    build: .
    image: keboola/pigeon
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
    environment:
      - KBC_PROJECTID

  ci-test:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "DYNAMO_TABLE=${TRAVIS_DYNAMO_TABLE}"
      - "EMAIL_DOMAIN=${TRAVIS_EMAIL_DOMAIN}"
      - "REGION=${TRAVIS_REGION}"
      - "S3_BUCKET=${TRAVIS_S3_BUCKET}"
      - "STACK_NAME=${TRAVIS_STACK_NAME}"
      - "USER_ACCESS_KEY_ID=${TRAVIS_USER_ACCESS_KEY_ID}"
      - "USER_SECRET_ACCESS_KEY=${TRAVIS_USER_SECRET_ACCESS_KEY}"
    command: >
           sh -c '
           ./vendor/bin/phpunit
           '
