version: "2"

services:

  app:
    build: .
    image: keboola/pigeon
    tty: true
    command: bash
    volumes:
      - ./:/code

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c './tests.sh'
    environment:
      -